name: SSH Git Pull and Run

on:
  push:
    branches:
      - master # Change this to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: appleboy/ssh-action@v1.0.0
      with:
            host: 34.173.56.83
            username: "praveengovi_nlp"
            key: ${{secrets.AIAAS_LLM_ACTIONS_KEY}}
            script: 
                    cd ~/AIaaS_Projects/AIaas_LLM/AIaaS_LLM/ 
                    git pull
                    cd ~
                    conda deactivate
                    source virtual_envs/venv_aiaas_llm/bin/activate
                    cd ~
                    ./start_aiaas_llam_api.py
